{% set name = "fairchem-core" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fairchem_core-{{ version }}.tar.gz
  sha256: 6fadd92a91a12252fb4357d2a23b2f25078c9db02dea69c810dd48c449bb0b33

build:
  entry_points:
    - fairchem = fairchem.core._cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.13
    - hatchling
    - hatch-vcs
    - hatch-fancy-pypi-readme >=24
    - pip
  run:
    - python >=3.9,<3.13
    - pytorch >=2.2
    - numpy >=1.25.0,<2.0.0
    - python-lmdb
    - ase
    - pymatgen >=2023.10.3
    - pytorch_geometric
    - pytorch_scatter
    - pyyaml
    - tensorboard
    - wandb
    - numba
    - e3nn >=0.5
    - requests
    - orjson
    - tqdm
    - submitit

test:
  imports:
    - fairchem.core
  commands:
    - fairchem --help

about:
  home: https://github.com/FAIR-Chem/fairchem
  summary: Machine learning models for use in catalysis as part of the Open Catalyst Project
  license: MIT
  license_file: src/fairchem/core/LICENSE.md

extra:
  recipe-maintainers:
    - jan-janssen
